version: '1'
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - db
    volumes:
      - "//%cd%/var/lib/postgresql/data"
    ports:
      - 5432:5432

  api:
    image: kijalxx/passengerpost
    ports:
      - 8081:8081
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/postgres
    networks:
      - db
    depends_on:
      - db

networks:
  db:
